version: "3.7"

services:
  mongo:
    image: mongo:6
    container_name: mongo-container
    restart: always
    # mapper port from host to container
    ports:
      - "27017:27017"
    # volumes keeps the data even if the container is removed
    volumes:
      - ./data:/data/db
  api:
    # build the image from the Dockerfile in the current directory
    # build: .
    container_name: api-container
    # now we are creating our app container from docker compose
    image: node:18
    working_dir: /usr/src/clean-node-api
    restart: always
    # this script will create a websocket to debug the application typescript
    command: bash -c "npm install && npm run debug"
    ports:
      - "5000:5000"
      - "9222:9222"
    # to connect to the mongo container
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
      - PORT=5000
    # to reflect the changes in the container
    # slash is to restart the container if any file changes
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    links:
      - mongo
